<?php //Do not edit this file by hand, it will be overwritten by the configuration utility. 
$WIKI_CONFIG['default_parser'] = 'MediaWiki';
$WIKI_CONFIG['default_lang'] = 'fr';
$WIKI_CONFIG['default_pdf_converter'] = 'mpdf';
?>
